"""attempt_record

Revision ID: 1047d4282964
Revises: 3644148c1885
Create Date: 2026-09-08 10:58:03.654067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1047d4282964'
down_revision: Union[str, Sequence[str], None] = '3644148c1885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attemptlog')
    op.drop_table('masteryrow')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('xp', sa.INTEGER(), nullable=False),
    sa.Column('streak', sa.INTEGER(), nullable=False),
    sa.Column('last_active_iso', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masteryrow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('skill', sa.VARCHAR(), nullable=False),
    sa.Column('mastery', sa.FLOAT(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attemptlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(), nullable=False),
    sa.Column('xp_awarded', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
