"""add_attempt_record_table

Revision ID: 92a71a1ace71
Revises: 1047d4282964
Create Date: 2026-09-08 13:04:45.326954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '92a71a1ace71'
down_revision: Union[str, Sequence[str], None] = '1047d4282964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attemptrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('timestamp_iso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attemptrecord')
    # ### end Alembic commands ###
